### ISSUE TITLE
Instructions are pretty thin...

### ISSUE THREAD

**Issue by jessenovotny** [learn-co-curriculum/login_required_lab#15]
Just an observation... if I hadn't peeked at the solution, I would have had no idea how to structure the pages for this lab.

hello.html.erb in views/application? 

> INSTRUCTIONS
> Build out the SessionsController. - including what actions??
> Write a current_user method. - where?
> Write a SecretsController using a before_action to prevent any route from being accessed without logging in. - okay this is more like it! :)

I LOVE nearly every lab I come across, so I feel the need to share my concerns when something seems really slapped together. I get that we need to take the training wheels off but a little more instruction on what's expected doesn't seem so out of line. 

In the real world I assume we're either getting detailed instruction from a boss or have free reign to build something with prewritten tests. Just my two cents :) Keep up the great work Team Learn!

**Comment by AnnJohn** [comment]
thanks for the great feedback @jessenovotny! This lab, you're right, can be improved. I'm going to keep this issue open and when we're able to fix this, we'll use your suggestions. thanks again!

**Comment by jessenovotny** [comment]
Thanks for listening to my concern :) I discovered that the very next
lesson discusses in great detail what we are trying to accomplish in this
lab. Perhaps, this lab could be moved up one, so to speak such that the
lesson teaches us what to do and then we practice it, just like nearly
every other lab. I get the feeling that was the original intention. And of
course, like I said before, the instructions could be more clear.

Cheers!
Jesse

**Comment by itzsaga** [comment]
This lab still seems to be in the wrong place. Placing it after "Sessions Controller" and "Sessions Controller Lab" makes more sense.

**Comment by jessenovotny** [comment]
Agreed.

**Comment by jmburges** [comment]
Hey @itzsaga and @jessenovotny thanks for catching this. We moved the labs around to be sessions and then this lab. 

As students get further and further into the course (and you're so far in! congrats 💯 ) we try and reduce the amount of explicit instructions. Sounds like we may have reduced the instructions too far on this one. We'll be sure to add some more instructions!
