### ISSUE TITLE
Learn IDE is getting stuck on Bundler

### ISSUE THREAD

**Issue by Cfrank482** [learn-co-curriculum/login_required_lab#19]
When trying to open the lesson through Learn IDE, I am getting this error:
Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    rails (~> 4.2.0) was resolved to 4.2.11, which depends on
      bundler (>= 1.3.0, < 2.0)
  Current Bundler version:
    bundler (2.0.0)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?
Could not find gem 'bundler (>= 1.3.0, < 2.0)', which is required by gem 'rails
(~> 4.2.0)', in any of the sources.

Have tried running 'gem install bundler', but it did not help.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
