### ISSUE TITLE
Broken application controller tests

### ISSUE THREAD

**Issue by MitulMistry** [learn-co-curriculum/login_required_lab#4]
The tests would fail and keep saying the current_user method was undefined for the application controller, even though I had written it in. I did some research and prepended the current_user method with the subject keyword in the spec file and that seemed to get it to register. I'm not fully sure if that's the right solution or how it works, but without it, it didn't seem current_user knew what class to be invoked upon.

**Comment by AnnJohn** [comment]
hi @MitulMistry thanks for raising this. We'll look into it, but for immediate help with the code and to see if there is an issue with the lesson, you can use the Ask a Question tool in Learn and someone from our support team will get back to you. Thanks.

**Comment by vicfriedman** [comment]
Hey @MitulMistry,

Thanks so much for pointing out this issue. The tests for current_user should actually be completely redesigned. You should never be calling a controller method just on it's own. I love the way you solved the problem for the time being, but you definitely uncovered a much bigger issue here. Thank you!

**Comment by victhevenot** [comment]
Hey @MitulMistry,

Thanks so much for bringing this issue to our attention! You definitely came up with a great solution. Had to look around and get some opinions, but it seems like your approach is the best way. Submitting a PR now. :)

**Comment by pletcher** [comment]
Resolved with #5
